# Generated by Django 3.2.6 on 2021-08-04 15:23

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corretora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField()),
                ('nome_completo', models.CharField(max_length=255, unique=True)),
                ('nome_exibir', models.CharField(max_length=255)),
                ('creat_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Corretoras',
            },
        ),
        migrations.CreateModel(
            name='Fluxo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(db_index=True, decimal_places=2, max_digits=19)),
                ('data', models.DateField(db_index=True)),
                ('creat_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Data')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('corretora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fl_corretora', to='fluxo.corretora')),
            ],
            options={
                'verbose_name': 'Fluxo',
                'verbose_name_plural': 'Fluxos',
                'ordering': ['data'],
            },
            managers=[
                ('fluxo_datable', django.db.models.manager.Manager()),
            ],
        ),
    ]
