# Generated by Django 3.2.6 on 2021-08-05 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluxo',
            name='tipo_fluxo',
            field=models.CharField(choices=[('en', 'Entrada'), ('sd', 'Saida')], db_index=True, default=1, max_length=2),
            preserve_default=False,
        ),
    ]
